### ISSUE TITLE
Horizontal scroll only not working on mousedown

### ISSUE THREAD

**Issue by einarolafs** [borbit/jquery.viewport#1]
There seem to be a problem where if the image has the same width as the container but is higher, when trying to drag it you don't see it move, just jumps to its position after I realize the mouse button. The image in which this problem occurs on is bigger than the container but been scaled down with css to fit the width of the container.

**Comment by borbit** [comment]
Can I see it live? Or drop the code right here please.

**Comment by einarolafs** [comment]
Don't remember why I did not reply, might have slipped my mind. Best just to close it :)
